version: '3.9'

services:

  scheduler-gdrive-move:
    image: mcuadros/ofelia:latest
    container_name: scheduler-gdrive-move
    depends_on:
      - gdrive-move-watch
      - gdrive-move-torrents
      - gdrive-move-nzb
    command: daemon --docker
    profiles:
      - fat
      - tiny
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-run.gdrive-move-watch.schedule: "@every 15s"
      ofelia.job-run.gdrive-move-watch.container: "gdrive-move-watch"
      ofelia.job-run.gdrive-move-torrents.schedule: "@every 25s"
      ofelia.job-run.gdrive-move-torrents.container: "gdrive-move-torrents"
      ofelia.job-run.gdrive-move-nzb.schedule: "@every 30s"
      ofelia.job-run.gdrive-move-nzb.container: "gdrive-move-nzb"

  gdrive-move-watch:
    image: rclone/rclone:1.59.2
    container_name: gdrive-move-watch
    command: "move ${GDRIVE_SERVICE}:/watch /source --log-level ${LOG_LEVEL} --stats 120s --buffer-size 16M --drive-chunk-size 16M --use-mmap --timeout 30s --config /config/rclone.conf"
    volumes:
      - ${STORAGE_LOCATION}/downloads/watch:/source
      - ${STORAGE_LOCATION}/gdrive:/config
    labels:
      - "group=storage"
    profiles:
      - fat
      - tiny

  gdrive-move-torrents:
    image: rclone/rclone:1.59.2
    container_name: gdrive-move-torrents
    command: "move /source ${GDRIVE_SERVICE}:/torrent/complete --log-level ${LOG_LEVEL} --delete-empty-src-dirs --stats 120s --buffer-size 128M --drive-chunk-size 128M --use-mmap --timeout 1m --transfers=4 --checkers=8 --bwlimit=${BWLIMIT} --config /config/rclone.conf"
    volumes:
      - ${STORAGE_LOCATION}/downloads/torrent/complete:/source
      - ${STORAGE_LOCATION}/gdrive:/config
    labels:
      - "group=storage"
    profiles:
      - fat
      - tiny

  gdrive-move-nzb:
    image: rclone/rclone:1.59.2
    container_name: gdrive-move-nzb
    command: "move /source ${GDRIVE_SERVICE}:/nzb/complete --log-level ${LOG_LEVEL} --delete-empty-src-dirs --stats 120s --buffer-size 128M --drive-chunk-size 128M --use-mmap --timeout 1m --exclude _unpack/ --transfers=4 --checkers=8 --bwlimit=${BWLIMIT} --config /config/rclone.conf"
    volumes:
      - ${STORAGE_LOCATION}/downloads/nzb/completed:/source
      - ${STORAGE_LOCATION}/gdrive:/config
    labels:
      - "group=storage"
    profiles:
      - fat
      - tiny

  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=${PUID}
      - PGID=${PUID}
      - TZ=${DOCKER_TZ}
    profiles:
      - fat
      - tiny
    volumes:
      - ${STORAGE_LOCATION}/nzbget:/config
      - ${STORAGE_LOCATION}/downloads/nzb:/downloads
      - ${STORAGE_LOCATION}/downloads/watch:/watch
    ports:
      - 6789:6789
    restart: unless-stopped

  autoremove-torrents:
    image: dantebarba/autoremove-torrents:1.7.1
    container_name: autoremove-torrents
    restart: unless-stopped
    volumes:
      - ${STORAGE_LOCATION}/autoremove-torrents/config.yml:/app/config.yml
    profiles:
      - tiny
    environment:
      TZ: ${DOCKER_TZ}
      CRON: ${CRON}
      OPTS: ${OPTS}


  qbittorrent:
    image: linuxserver/qbittorrent:14.3.2.99202012272006-7195-abb854a1eubuntu18.04.1-ls107
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${DOCKER_TZ}
      - WEBUI_PORT=8080
    profiles:
      - fat
      - tiny
    volumes:
      - ${STORAGE_LOCATION}/qbittorrent:/config
      - ${STORAGE_LOCATION}/downloads/torrent:/downloads
      - ${STORAGE_LOCATION}/downloads/watch:/watch
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped

  tracker-annunce:
    image: dantebarba/torrent-scripts:latest
    container_name: tracker-annunce
    profiles:
      - fat
      - tiny
    environment: 
      QBT_USERNAME: ${QBT_USERNAME}
      QBT_PASSWORD: ${QBT_PASSWORD}
      CMD: "/bin/bash /Scripts/AddqBittorrentTrackers.sh ."
      TZ: ${DOCKER_TZ}
      CRON: '*/5 * * * *'
    restart: unless-stopped

  rclone-sa-autoswap:
    image: dantebarba/rclone-sa-autoswap:latest
    container_name: rclone-sa-autoswap
    profiles:
      - fat
      - tiny
    volumes:
      - ${STORAGE_LOCATION}/gdrive:/config
    environment:
      CRON: ${AUTOSWAP_CRON} # will renew the SA number once every hour
      MAX_NUMBER: ${SA_NUMBER} # the number of SAs you generated
      PREFIX: ${SA_PREFIX} # the prefix with path included before the SA Number.
      # SAs should be named with the following schema: my-sa-{number}.json where number is the SA designated number.
      # this number should be sequential, from 1 to n.