version: '3.9'

services:
  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=${PUID}
      - PGID=${PUID}
      - TZ=${DOCKER_TZ}
    profiles:
      - fat
      - tiny
    volumes:
      - ${STORAGE_LOCATION}/nzbget:/config
      - ${STORAGE_LOCATION}/downloads/nzb:/downloads
      - ${STORAGE_LOCATION}/downloads/watch:/watch
    ports:
      - 6789:6789
    restart: unless-stopped

  autoremove-torrents:
    image: dantebarba/autoremove-torrents:1.7.1
    container_name: autoremove-torrents
    restart: unless-stopped
    volumes:
      - ${STORAGE_LOCATION}/autoremove-torrents/config.yml:/app/config.yml
    profiles:
      - tiny
    environment:
      TZ: ${DOCKER_TZ}
      CRON: ${CRON}
      OPTS: ${OPTS}

  qbittorrent:
    image: linuxserver/qbittorrent:14.3.2.99202012272006-7195-abb854a1eubuntu18.04.1-ls107
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${DOCKER_TZ}
      - WEBUI_PORT=8080
    profiles:
      - fat
      - tiny
    volumes:
      - ${STORAGE_LOCATION}/qbittorrent:/config
      - ${STORAGE_LOCATION}/downloads/torrent:/downloads
      - ${STORAGE_LOCATION}/downloads/watch:/watch
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped

  tracker-annunce:
    image: dantebarba/torrent-scripts:latest
    container_name: tracker-annunce
    profiles:
      - fat
      - tiny
    environment: 
      QBT_USERNAME: ${QBT_USERNAME}
      QBT_PASSWORD: ${QBT_PASSWORD}
      CMD: "/bin/bash /Scripts/AddqBittorrentTrackers.sh ."
      TZ: ${DOCKER_TZ}
      CRON: '*/5 * * * *'
    restart: unless-stopped