version: '3.7'

services:
  gdrive-mount:
    image: rclone/rclone:beta
    container_name: gdrive-mount
    restart: unless-stopped
    command: "mount gdrive-watch: /mnt/gdrive --config=/config/rclone/rclone.conf --allow-other --gid ${PGID} --uid ${PUID} --log-level ${LOG_LEVEL} --stats 10m --use-mmap --timeout 5m --dir-cache-time 30s --umask 002"
    volumes:
      - ${STORAGE_LOCATION}/gdrive:/config/rclone
      - /mnt/gdrive:/mnt/gdrive:shared
    privileged: true
    devices:
      - /dev/fuse
    cap_add:
      - MKNOD
      - SYS_ADMIN
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      LOG_LEVEL: ${LOG_LEVEL}
      TZ: ${DOCKER_TZ}

  gdrive-move:
    image: pfidr/rclone:latest
    container_name: gdrive-move
    restart: unless-stopped
    volumes:
      - ${TORRENT_CACHE}/downloads/complete:/source
      - ${STORAGE_LOCATION}/gdrive:/config
    environment:
      SYNC_SRC: /source
      SYNC_DEST: gdrive:/complete
      SYNC_OPTS: '--log-level ${LOG_LEVEL} --delete-empty-src-dirs --progress --buffer-size 256M --drive-chunk-size 256M --use-mmap --timeout 1m --stats 120s'
      RCLONE_DIR_CHECK_SKIP: 'true'
      RCLONE_CMD: move
      TZ: ${DOCKER_TZ}
      CRON: '* * * * *'
      UID: ${PUID}
      GID: ${PGID}


  autoremove-torrents:
    image: dantebarba/autoremove-torrents:2.0.0
    container_name: autoremove-torrents
    restart: unless-stopped
    volumes:
      - ${STORAGE_LOCATION}/autoremove-torrents/config.yml:/app/config.yml
    environment:
      TZ: ${DOCKER_TZ}
      CRON: ${CRON}
      OPTS: ${OPTS}


  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${DOCKER_TZ}
      - WEBUI_PORT=8080
    volumes:
      - ${STORAGE_LOCATION}/qbittorrent:/config
      - ${TORRENT_CACHE}/downloads:/downloads
      - /mnt/gdrive:/watch
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped

  deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${DOCKER_TZ}
      - DELUGE_LOGLEVEL=${LOG_LEVEL_DELUGE} 
    volumes:
      - ${STORAGE_LOCATION}/deluge:/config
      - ${TORRENT_CACHE}:/downloads
      - /mnt/gdrive/watch:/watch
    restart: unless-stopped

  transmission:
    image: "linuxserver/transmission"
    container_name: transmission
    hostname: transmission
    restart: unless-stopped
    volumes:
      - "${STORAGE_LOCATION}/transmission/config:/config"
      - "${TORRENT_CACHE}/incomplete:/downloads/incomplete"
      - "/mnt/gdrive/complete:/downloads/complete"
      - "/mnt/gdrive/watch:/watch"
      - "/etc/localtime:/etc/localtime:ro"
      - "./wait-for-it.sh:/wait-for-it.sh"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${DOCKER_TZ}
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    depends_on:
      - gdrive-mount
